name: Run Network Deployment Pytorch Tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      converter-version:
        required: true
        type: string
      tpc-version:
        required: true
        type: string
      onnx-opset-version:
        required: false
        type: string
        default: "20"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup MCT environment
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "torch<2.7" "torchvision<0.22" "onnx<1.18" "onnxruntime<1.22" "onnxruntime-extensions<0.14"
          pip install pytest pytest-mock
          pip list | grep -e mct -e edge -e onnx
      - name: Run MCT test
        env:
          TPC_VERSION: ${{ inputs.tpc-version }}
          ONNX_OPSET_VERSION: ${{ inputs.onnx-opset-version }}
        run: |
          pytest network_deployment_tests/pytorch/test_run_mct.py -s
      - name: Uninstall MCTQ and CustomLayer
        run: |
          pip uninstall -y mct-quantizers edge-mdt-cl
      - name: Setup Converter environment
        run: |
          pip install imx500-converter[pt]==${{ inputs.converter-version }}
          pip list | grep -e mct -e edge -e onnx -e imx500
      - name: Run Converter test
        run: |
          pytest network_deployment_tests/pytorch/test_run_converter.py -s