name: Run Keras Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      tf-version:
        required: true
        type: string

jobs:
  run-tensorflow-tests:
    #  Tensorflow uses Numpy<2,
    #  so it does not support testing by Numpy version (<2.4 or 2.4) as seen in Pytorch (run_pytorch_tests.yml).
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: |    
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install tensorflow==${{ inputs.tf-version }}
          pip install pytest pytest-mock
          pip list | grep -e tensorflow -e numpy
          pip check
      - name: Run pytest
        run: |
          pytest tests_pytest/keras_tests
      - name: Run unittests
        run: |
          python -m unittest discover tests/keras_tests -v

