name: Run PyTorch Tests

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      torch-version:
        required: true
        type: string

jobs:
  run-pytorch-tests:
    #  Regression testing for Numpy 2.4.
    #  It was performed on combinations of Python (3.10, 3.11, 3.12), Pytorch (2.3, 2.4, 2.5, 2.6),
    #  and NumPy (<2.4 or 2.4) versions.
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "${{ inputs.python-version }}" ]
        np_ver: [ "<2.4", "2.4" ]
        exclude:
          - np_ver: "2.4"
            python-version: "3.10"  # Numpy 2.4 is not supported on Python 3.10
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        #  For Python 3.10, no need to reinstall Numpy<2.4 because it is installed in requirements.txt.
        #  For Python 3.11 and 3.12, Numpy<2.4 is reinstalled after Numpy 2.4 is installed in requirements.txt.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt          
          pip install torch==${{ inputs.torch-version }} torchvision onnx onnxruntime "onnxruntime-extensions<0.14"
          if [ "${{ matrix.np_ver }}" == "<2.4" ] && [ "${{ matrix.python-version }}" != "3.10" ]; then
            echo "Installing numpy<2.4"
            pip install numpy 'numpy<2.4'
          fi
          pip install pytest pytest-mock
          pip list | grep -e torch -e onnx -e numpy
          pip check
      - name: Run pytest
        run: |
          pytest tests_pytest/pytorch_tests -s
      - name: Run unittests
        run: |
          python -m unittest discover tests/pytorch_tests -v


